
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./files_csv:/app/files_csv
      - ./parquet_files:/app/parquet_files
      - ./model:/app/model
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000