services:
  app:
    image: datathon-app
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "app.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8009",
      ]
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8009:8009
    env_file:
      - .env
volumes:
  postgres_data:

networks:
  docker_compose:
